name: Greetings

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'DependaBot'' first issue'
        pr_message: 'DependaBot'' first pr'